baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.

sass:
    style: :compressed

timezone: America/New_York
future: false

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
